name: Production CI/CD
on:
  push:
    tags:
      - production/*
env:
  # How to sync these vars with other repos?
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_GITHUB_CI_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_GITHUB_CI_AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}
  AWS_REGION: us-west-2
  ROOT_DOMAIN: strn.network
  BUCKET: filecoin-saturn
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        env:
          BUCKET_NAME: "filecoin-saturn-terraform"
          STATE_KEY: "rc-production.tfstate"
        run: |
          terraform init \
            -backend-config="bucket=${BUCKET_NAME}" \
            -backend-config="key=${STATE_KEY}" \
            -backend-config="region=${AWS_REGION}"

      - name: Terraform Apply
        env:
          TF_VAR_allowed_account_ids: '["${{secrets.PROD_AWS_ACCOUNT_NUMBER}}"]'
          TF_VAR_database_user: ${{ secrets.PROD_POSTGRES_DB_USER }}
          TF_VAR_database_password: ${{ secrets.PROD_POSTGRES_DB_PASSWORD }}
        run: |
          mv production.tfvars terraform.tfvars
          cat terraform.tfvars
          terraform apply -var-file="terraform.tfvars" --auto-approve
